### ISSUE TITLE
pcap.h No such file or directory

### ISSUE THREAD

**Issue by Aifolin** [adedayo/tcpscan#1]
go get github.com/adedayo/tcpscan
# github.com/google/gopacket/pcap
../github.com/google/gopacket/pcap/pcap.go:22:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.

**Comment by adedayo** [comment]
You need libpcap to build the project. Please get it from tcpdump https://github.com/the-tcpdump-group/libpcap
